/// Flutter icons MikesIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MikesIcons
///      fonts:
///       - asset: fonts/MikesIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MikesIcons {
  MikesIcons._();

  static const _kFontFam = 'MikesIcons';

  static const IconData airplanemode_active = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData adb = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData traffic_cone = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData police = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData heart_pulse = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData construction = const IconData(0xe841, fontFamily: _kFontFam);
}
